### ISSUE TITLE
Do not see the code button to download zip

### ISSUE THREAD

**Issue by JuanMontano10** [LinkedInLearning/learning-linux-command-line-3005201#1]
Apart from this problem, when downloading the gcc part it doesnt prompt me to run software. When I open that file and click run software nothing happens. So I cant edit my view per the course instructions.

**Comment by yousseffahmy** [comment]
@scottsimpson

**Comment by tnaseef** [comment]
I have both the same issues - can't run Guest Additions once I've inserted the CD image, and can't find the download for the code in this repository.

**Comment by Cinrobru** [comment]
I have the same issues - can't run Guest additions and do not have the green code button to download the exercises in this repository.

**Comment by kchang1997** [comment]
Change your zoom level from 100% to something smaller. Then it should show up. It worked for me.

**Comment by blackth0rn3** [comment]
I have the same issues posted above.

**Comment by valo-16** [comment]
Same issues.

**Comment by TAH92-PITT** [comment]
Same issues , I cannot download zip file

**Comment by s209220** [comment]
So it looks like multiple learners have the same issue as mine. I also faced both the above issues. The course is good, but without the repository files it's difficult to continue.

**Comment by scottsimpson** [comment]
Hello-

It seems many people are having the same set of issues with this course, so hopefully these tips can resolve them.

### Downloading the Zip File

To download the zip file from GitHub, click the Code button at the top right of the repository page, and then click the Download ZIP item:

<img width="544" alt="Screen Shot 2022-10-17 at 11 15 39 AM" src="https://user-images.githubusercontent.com/941181/196254167-d898f897-93e5-4ea8-ad40-8b655612aaa2.png">

If you don't see the green Code button in your browser, your browser window may be too narrow. Expand the width of the window or zoom out to see if the button appears.

### Installing Guest Additions

First, open the Terminal application and type the command:

```bash
sudo apt install gcc make perl
```

Then, use the VirtualBox interface to insert the Guest Additions CD image.

To install the Guest Additions software, find the CD in the bar at the left of the screen, and click it to open the file browser.

<img width="196" alt="Screen Shot 2022-10-17 at 11 21 33 AM" src="https://user-images.githubusercontent.com/941181/196254293-b4a2c248-d13f-462d-b743-3bc5889e95d1.png">

Then, select the file `autorun.sh`, right click it, and click 'Run as a Program':

<img width="776" alt="Screen Shot 2022-10-17 at 11 21 07 AM" src="https://user-images.githubusercontent.com/941181/196255268-fc3fc56b-fe8f-42da-bb72-9b63f18eaf3d.png">

When the process completes, press return and then restart your virtual machine.
