### ISSUE TITLE
PLEASE FIX

### ISSUE THREAD

**Issue by RickOttolino** [LinkedInLearning/learning-linux-command-line-3005201#2]
VBoxGuestAdditions does not work and ZIP file with Exercises are unavailable

## Issue Overview
VBoxGuestAdditions does not work and ZIP file with Exercises are unavailable

## Describe your environment
 Running Ubuntu as a VM on a WIN10 Machine

## Steps to Reproduce

1.
2.
3.
4.

**Comment by hiteshujani2002** [comment]
I am also facing the same issue...

**Comment by scottsimpson** [comment]
Closing as duplicate of #1.
